# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  name: "RestoreNuget"
  inputs:
    command: 'restore'
    projects: '**\*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: "PublishApi"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r linux-x64 --output $(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: 'ApiArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'API'
    publishLocation: 'Container'

- task: DeleteFiles@1
  name: 'DeleteApiFiles'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: VSBuild@1
  name: 'BuildSQL'
  inputs:
    solution: 'RMData/RMData.sqlproj'
    msbuildArgs: '/p:OutDir="$(build.artifactStagingDirectory)" /property:DSP="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  name: 'SqlArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SqlDrop'
    publishLocation: 'Container'

- task: DeleteFiles@1
  name: 'DeleteSqlFiles'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/*.json'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'RMDesktopUI/RMDesktopUI.csproj'
    arguments: '-p:PublishSingleFile=true  -c Release --runtime win-x64 --self-contained true --output $(build.artifactStagingDirectory)'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  name: 'WPFArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'WPF'
    publishLocation: 'Container'

- task: DeleteFiles@1
  name: 'DeleteWPFFiles'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: CmdLine@2
  inputs:
    script: |
      dotnet tool install --global dotnet-ef
      dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\migrate.sql -p RMApi\RMApi.csproj

- task: PublishBuildArtifacts@1
  name: 'AuthDbArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AuthDb'
    publishLocation: 'Container'